import { Injectable } from '@nestjs/common';
import { AIReviewResult, CodeIssue } from './ai-review.service';

@Injectable()
export class CommentFormatterService {
  /**
   * 格式化 MR 级别的总评评论（CodeRabbit 风格）
   */
  formatSummaryComment(reviewResult: AIReviewResult): string {
    const { summary, issues, score, metrics, suggestions } = reviewResult;
    
    // 统计不同严重程度的问题
    const issueStats = this.categorizeIssues(issues);
    
    // 选择总体评估的 emoji
    const severityEmoji = this.getSeverityEmoji(summary.severity);
    
    // 生成 Markdown 格式的评论
    const markdown = `## 🤖 AI Code Review

### 📊 Review Score: ${score}/100

**Overall Assessment**: ${severityEmoji} ${summary.description}

### 📈 Quality Metrics
- 🔒 Security: ${metrics.security}/100
- ⚡ Performance: ${metrics.performance}/100
- 🛠️ Maintainability: ${metrics.maintainability}/100
- 🎯 Reliability: ${metrics.reliability}/100

### ⚠️ Issues Found
- 🔴 Error: ${issueStats.error} issues
- 🟡 Warning: ${issueStats.warning} issues
- 🔵 Info: ${issueStats.info} issues

${this.formatIssuesList(issues)}

${suggestions && suggestions.length > 0 ? this.formatSuggestions(suggestions) : ''}

---
*🚀 Generated by MoonLens AI Review*
`;

    return markdown;
  }

  /**
   * 格式化单个内联评论
   */
  formatInlineComment(issue: CodeIssue): string {
  const severityEmoji = this.getIssueSeverityEmoji(issue.severity);
  const typeLabel = this.getIssueTypeLabel(issue.type);

  // 注意：必须使用真实换行（\n），否则 GitLab 不会识别 suggestion 代码块
  let markdown = `**${severityEmoji} ${typeLabel}**: ${issue.title}\n\n`;
  markdown += `${issue.description}\n\n`;

  if (issue.suggestion) {
    markdown += `**\ud83d\udca1 Suggestion**: ${issue.suggestion}\n\n`;
  }

  // 如果提供了可直接应用的代码替换，上网 GitLab suggestion 块以支持“Apply suggestion”
  // GitLab 要求 MR diff 内讨论 + ```suggestion ... ``` 才会呈现按钮
  if (issue.codeExample?.after) {
    markdown += `\n\n【代码建议可直接应用】\n`;
    markdown += "```suggestion\n" + issue.codeExample.after + "\n```\n";
  } else if (issue.code) {
    // 向下兼容：没有 after 时，仍尝试用 suggestion 包裹现有代码，便于一键应用后再微调
    markdown += "```suggestion\n" + issue.code + "\n```\n";
  }

  return markdown;
}

  /**
   * 格式化 issues 列表（用于总评中）
   */
  private formatIssuesList(issues: CodeIssue[]): string {
    if (!issues || issues.length === 0) {
      return '### ✅ No Issues Found\n\nGreat job! The code looks clean.\n';
    }

    let markdown = '### 📋 Detailed Issues\n\n';
    
    // 按严重程度分组
    const grouped = {
      error: issues.filter(i => i.severity === 'error'),
      warning: issues.filter(i => i.severity === 'warning'),
      info: issues.filter(i => i.severity === 'info'),
    };

    // 输出每个分组
    for (const [severity, severityIssues] of Object.entries(grouped)) {
      if (severityIssues.length === 0) continue;
      
      const emoji = this.getIssueSeverityEmoji(severity as any);
      markdown += `#### ${emoji} ${severity.toUpperCase()}\n\n`;
      
      severityIssues.forEach((issue, index) => {
        const typeLabel = this.getIssueTypeLabel(issue.type);
        markdown += `${index + 1}. **${typeLabel}** in \`${issue.file}:${issue.line}\`\n`;
        markdown += `   - ${issue.title}\n`;
        if (issue.suggestion) {
          markdown += `   - 💡 ${issue.suggestion}\n`;
        }
        markdown += '\n';
      });
    }

    return markdown;
  }

  /**
   * 格式化建议列表
   */
  private formatSuggestions(suggestions: string[]): string {
    let markdown = '### 💡 Key Suggestions\n\n';
    suggestions.forEach((suggestion, index) => {
      markdown += `${index + 1}. ${suggestion}\n`;
    });
    return markdown + '\n';
  }

  /**
   * 统计不同严重程度的问题数量
   */
  private categorizeIssues(issues: CodeIssue[]): {
    error: number;
    warning: number;
    info: number;
  } {
    return {
      error: issues.filter(i => i.severity === 'error').length,
      warning: issues.filter(i => i.severity === 'warning').length,
      info: issues.filter(i => i.severity === 'info').length,
    };
  }

  /**
   * 获取总体严重程度的 emoji
   */
  private getSeverityEmoji(severity: 'success' | 'warning' | 'error' | 'info'): string {
    const emojiMap = {
      success: '✅',
      warning: '⚠️',
      error: '🔴',
      info: 'ℹ️',
    };
    return emojiMap[severity] || 'ℹ️';
  }

  /**
   * 获取问题严重程度的 emoji
   */
  private getIssueSeverityEmoji(severity: 'error' | 'warning' | 'info'): string {
    const emojiMap = {
      error: '🔴',
      warning: '🟡',
      info: '🔵',
    };
    return emojiMap[severity] || '🔵';
  }

  /**
   * 获取问题类型的标签
   */
  private getIssueTypeLabel(type: string): string {
    const labelMap = {
      security: '🔐 Security',
      performance: '⚡ Performance',
      quality: '✨ Code Quality',
      style: '🎨 Style',
      bug: '🐛 Bug',
    };
    return labelMap[type] || type;
  }
}
